"""Canonical observation identity module.

Contract:
- observation.observation_id is the caller-supplied logical identity.
- Required, persisted verbatim, and never transformed or generated by the integrity layer.
- Example: Group 3's ``TC-Z03-F02-LIDAR-OBS001`` is persisted unchanged as ``TC-Z03-F02-LIDAR-OBS001``.
"""

from __future__ import annotations

from typing import Any


def resolve_observation_id(payload: dict[str, Any]) -> str:
    """Extract and validate the caller-supplied canonical observation_id verbatim.

    Supports top-level ``payload['observation_id']`` or nested ``payload['observation']['observation_id']``.
    Raises ``ValueError`` if observation_id is missing or empty.
    """
    obs_id = payload.get("observation_id")
    if not obs_id and isinstance(payload.get("observation"), dict):
        obs_id = payload["observation"].get("observation_id")

    if not obs_id or not isinstance(obs_id, str) or not obs_id.strip():
        raise ValueError("Caller-supplied observation_id is required and must be a non-empty string")

    return obs_id.strip()


def participating_fields() -> list[str]:
    """Document that logical identity is caller-supplied verbatim."""
    return ["observation_id (caller-supplied primary key)"]

